@startuml
object Kunde {
+Kontaktinformationer
}
object Sælger {
(Som udgangspunkt én sælger pr. kunde,
men i tilfælde af fravær skal sælgerne
kunne servicere hinandens kunder)
}
object Admin {
(En eller flere admins,
som har de fulde rettigheder til systemet)
}
object Carport {
+Stolper
+Rem
+Spær
+Stern
+Hulbånd
+Tagbeklædning
+Søm, skruer, beslag
+Evt. skur
+Evt. vægbeklædning
}
object Stykliste
object Tegningssæt {
+Tegning fra siden
+Tegning fra oven
+Evt. 3D tegning
}
object Ordre {
+Ordrenr.
+Dato
+Total kostpris ekskl. moms
+Total salgspris inkl. moms
+Justeret dækningsgrad
}
object Ordrelinje {
+Varenr.
+Antal
+Pris for dette antal
}
object Vare{
(Alle varer i Fogs sortiment)
+Varenr.
+Beskrivelse
+Kostpris ekskl. moms
+Salgspris inkl. moms
+Dækningsgrad
}

Kunde "1" -- "1..*" Ordre
Ordre "1" -- "1" Carport
Carport "1" -- "1" Tegningssæt
Carport "1" -- "1" Stykliste
Stykliste "1" -- "*" Ordrelinje
Vare "1" -- "0..*" Ordrelinje

@enduml